=== robertmue/systo-resources/schemas/systo_schema_v1.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Systo model schema",
    "type": "object",
    "properties": {
        "meta": {
            "description": "Additional information about the model. Validated at http://www.jsonschemavalidator.net/",
            "type": "object",
            "properties": {
            }
        },
        "nodes": {
            "description": "The node map - i.e. the set of all nodes",
            "type": "object",
            "additionalProperties": {
                "description": "Information about each node",
                "type": "object",
                "properties": {
                    "id": {
                        "description": "",
                        "type": "string"
                    },
                    "type": {
                        "description": "",
                        "type": "string"
                    },
                    "label": {
                        "description": "",
                        "type": "string"
                    },
                    "centrex": {
                        "description": "",
                        "type": "number"
                    },
                    "centrey": {
                        "description": "",
                        "type": "number"
                    },
                    "text_shiftx": {
                        "description": "",
                        "type": "number"
                    },
                    "text_shifty": {
                        "description": "",
                        "type": "number"
                    },
                    "extras": {
                        "description": "",
                        "type": "object",
                        "properties": {
                            "equation": {
                                "description": "",
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "description": "",
                                        "type": "string"
                                    },
                                    "default_value": {
                                        "description": "",
                                        "type": "string"
                                    },
                                    "value": {
                                        "description": "",
                                        "type": "string"
                                    }
                                }
                            },
                            "min_value": {
                                "description": "",
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "description": "",
                                        "type": "string"
                                    },
                                    "default_value": {
                                        "description": "",
                                        "type": "number"
                                    },
                                    "value": {
                                        "description": "",
                                        "type": "number"
                                    }
                                }
                            },
                            "max_value": {
                                "description": "",
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "description": "",
                                        "type": "string"
                                    },
                                    "default_value": {
                                        "description": "",
                                        "type": "number"
                                    },
                                    "value": {
                                        "description": "",
                                        "type": "number"
                                    }
                                }
                            },
                            "documentation": {
                                "description": "",
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "description": "",
                                        "type": "string"
                                    },
                                    "default_value": {
                                        "description": "",
                                        "type": "string"
                                    },
                                    "value": {
                                        "description": "",
                                        "type": "string"
                                    }
                                }
                            },
                            "comments": {
                                "description": "",
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "description": "",
                                        "type": "string"
                                    },
                                    "default_value": {
                                        "description": "",
                                        "type": "string"
                                    },
                                    "value": {
                                        "description": "",
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "arcs": {
            "description": "The arc (edge) map - i.e. the set of all edges",
            "type": "object",
            "additionalProperties": {
                "description": "Information about each node",
                "type": "object",
                "properties": {
                    "id": {
                        "description": "",
                        "type": "string"
                    },
                    "type": {
                        "description": "",
                        "type": "string"
                    },
                    "label": {
                        "description": "",
                        "type": "string"
                    },
                    "start_node_id": {
                        "description": "",
                        "type": "string"
                    },
                    "end_node_id": {
                        "description": "",
                        "type": "string"
                    },
                    "curvature": {
                        "description": "",
                        "type": "number"
                    },
                    "along": {
                        "description": "",
                        "type": "number"
                    },
                    "shape": {
                        "description": "",
                        "type": "string"
                    },
                    "set_state": {
                        "description": "",
                        "type": "string"
                    },
                    "select_state": {
                        "description": "",
                        "type": "string"
                    },
                    "line_colour": {
                        "description": "",
                        "type": "string"
                    },
                    "line_width": {
                        "description": "",
                        "type": "number"
                    },
                    "fill_colour": {
                        "description": "",
                        "type": "string"
                    },
                    "arrowhead": {
                        "description": "",
                        "type": "object",
                        "properties": {
                            "shape": {
                                "description": "",
                                "type": "string"
                            },
                            "gap": {
                                "description": "",
                                "type": "number"
                            },
                            "width": {
                                "description": "",
                                "type": "number"
                            },
                            "front": {
                                "description": "",
                                "type": "number"
                            },
                            "back": {
                                "description": "",
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "scenarios": {
            "description": "The model run-time scenarios",
            "type": "object",
            "additionalProperties": {
                "description": "",
                "type": "object",
                "properties": {
                    "start_time": {
                        "description": "",
                        "type": "number"
                    },
                    "end_time": {
                        "description": "",
                        "type": "number"
                    },
                    "nstep": {
                        "description": "",
                        "type": "number"
                    },
                    "display_interval": {
                        "description": "",
                        "type": "number"
                    },
                    "integration_method": {
                        "description": "",
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== robertmue/systo-resources/models/gallery/gallery001.json
{  "meta": {
      "language": "system_dynamics",
      "id": "gallery001",
      "name": "single_stock_constant_inflow",
      "label": "Single stock, constant inflow"
   },
   "nodes": {
      "stock1": {
         "id": "stock1",
         "type": "stock",
         "label": "stock1",
         "centrex": 341,
         "centrey": 133,
         "text_shiftx": 1,
         "text_shifty": -22,
         "extras": {
            "equation": {
               "type": "long_text",
               "default_value": "",
               "value": "0"
            },
            "min_value": {
               "type": "short_text",
               "default_value": 0,
               "value": 0
            },
            "max_value": {
               "type": "short_text",
               "default_value": 100,
               "value": 100
            },
            "documentation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "comments": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            }
         }
      },
      "cloud1": {
         "id": "cloud1",
         "type": "cloud",
         "label": "cloud1",
         "centrex": 201,
         "centrey": 134,
         "text_shiftx": 0,
         "text_shifty": 25,
         "extras": {
            "equation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "min_value": {
               "type": "short_text",
               "default_value": 0,
               "value": 0
            },
            "max_value": {
               "type": "short_text",
               "default_value": 100,
               "value": 100
            },
            "documentation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "comments": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            }
         }
      },
      "valve1": {
         "id": "valve1",
         "type": "valve",
         "label": "inflow",
         "centrex": 271,
         "centrey": 133.5,
         "text_shiftx": 0,
         "text_shifty": 19,
         "extras": {
            "equation": {
               "type": "long_text",
               "default_value": "",
               "value": "2"
            },
            "min_value": {
               "type": "short_text",
               "default_value": 0,
               "value": 0
            },
            "max_value": {
               "type": "short_text",
               "default_value": 10,
               "value": 10
            },
            "documentation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "comments": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            }
         }
      }
   },
   "arcs": {
      "flow1": {
         "id": "flow1",
         "type": "flow",
         "label": "flow1",
         "start_node_id": "cloud1",
         "end_node_id": "stock1",
         "curvature": 0.3,
         "along": 0.5,
         "select_state": "normal",
         "set_state": "set",
         "node_id": "valve1",
         "shape": "straight",
         "line_colour": "#a0a0a0",
         "line_width": 4,
         "fill_colour": "#a0a0a0",
         "arrowhead": {
            "shape": "diamond",
            "gap": 6,
            "width": 5,
            "front": 12,
            "back": 0
         }
      }
   },
   "scenarios": {
      "default": {
         "simulation_settings": {
            "start_time": 0,
            "end_time": 100,
            "nstep": 100,
            "display_interval": 1,
            "integration_method": "euler1"
         }
      }
   }
}

=== robertmue/systo-resources/models/tank.json
{
   "meta": {
      "language": "system_dynamics",
      "id": "aeri_nyoc"
   },
   "nodes": {
      "stock1": {
         "id": "stock1",
         "type": "stock",
         "label": "tank",
         "centrex": 339,
         "centrey": 131,
         "text_shiftx": 1,
         "text_shifty": -22,
         "extras": {
            "equation": {
               "type": "long_text",
               "default_value": "",
               "value": "0"
            },
            "min_value": {
               "type": "short_text",
               "default_value": 0,
               "value": 0
            },
            "max_value": {
               "type": "short_text",
               "default_value": 100,
               "value": 100
            },
            "documentation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "comments": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            }
         }
      },
      "cloud1": {
         "id": "cloud1",
         "type": "cloud",
         "label": "cloud1",
         "centrex": 171,
         "centrey": 132,
         "text_shiftx": 0,
         "text_shifty": 25,
         "extras": {
            "equation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "min_value": {
               "type": "short_text",
               "default_value": 0,
               "value": 0
            },
            "max_value": {
               "type": "short_text",
               "default_value": 100,
               "value": 100
            },
            "documentation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "comments": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            }
         }
      },
      "valve1": {
         "id": "valve1",
         "type": "valve",
         "label": "inflow",
         "centrex": 255,
         "centrey": 131.5,
         "text_shiftx": 0,
         "text_shifty": 19,
         "extras": {
            "equation": {
               "type": "long_text",
               "default_value": "",
               "value": "10"
            },
            "min_value": {
               "type": "short_text",
               "default_value": 0,
               "value": 0
            },
            "max_value": {
               "type": "short_text",
               "default_value": 10,
               "value": 10
            },
            "documentation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "comments": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            }
         }
      },
      "cloud2": {
         "id": "cloud2",
         "type": "cloud",
         "label": "cloud2",
         "centrex": 483,
         "centrey": 133,
         "text_shiftx": 0,
         "text_shifty": 25,
         "extras": {
            "equation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "min_value": {
               "type": "short_text",
               "default_value": 0,
               "value": 0
            },
            "max_value": {
               "type": "short_text",
               "default_value": 100,
               "value": 100
            },
            "documentation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "comments": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            }
         }
      },
      "valve2": {
         "id": "valve2",
         "type": "valve",
         "label": "outflow",
         "centrex": 411,
         "centrey": 132,
         "text_shiftx": 0,
         "text_shifty": 19,
         "extras": {
            "equation": {
               "type": "long_text",
               "default_value": "",
               "value": "outflow_coef*tank"
            },
            "min_value": {
               "type": "short_text",
               "default_value": 0,
               "value": 0
            },
            "max_value": {
               "type": "short_text",
               "default_value": 10,
               "value": 10
            },
            "documentation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "comments": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            }
         }
      },
      "variable1": {
         "id": "variable1",
         "type": "variable",
         "label": "outflow_coef",
         "centrex": 386,
         "centrey": 181,
         "text_shiftx": 0,
         "text_shifty": 0,
         "extras": {
            "equation": {
               "type": "long_text",
               "default_value": "",
               "value": "0.05"
            },
            "min_value": {
               "type": "short_text",
               "default_value": 0,
               "value": 0
            },
            "max_value": {
               "type": "short_text",
               "default_value": 1,
               "value": 1
            },
            "documentation": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            },
            "comments": {
               "type": "long_text",
               "default_value": "",
               "value": ""
            }
         }
      }
   },
   "arcs": {
      "flow1": {
         "id": "flow1",
         "type": "flow",
         "label": "flow1",
         "start_node_id": "cloud1",
         "end_node_id": "stock1",
         "curvature": 0.3,
         "along": 0.5,
         "select_state": "normal",
         "set_state": "set",
         "node_id": "valve1",
         "shape": "straight",
         "line_colour": "#a0a0a0",
         "line_width": 4,
         "fill_colour": "#a0a0a0",
         "arrowhead": {
            "shape": "diamond",
            "gap": 6,
            "width": 5,
            "front": 12,
            "back": 0
         }
      },
      "flow2": {
         "id": "flow2",
         "type": "flow",
         "label": "flow2",
         "start_node_id": "stock1",
         "end_node_id": "cloud2",
         "curvature": 0.3,
         "along": 0.5,
         "select_state": "normal",
         "set_state": "set",
         "node_id": "valve2",
         "shape": "straight",
         "line_colour": "#a0a0a0",
         "line_width": 4,
         "fill_colour": "#a0a0a0",
         "arrowhead": {
            "shape": "diamond",
            "gap": 6,
            "width": 5,
            "front": 12,
            "back": 0
         }
      },
      "influence1": {
         "id": "influence1",
         "type": "influence",
         "label": "influence1",
         "start_node_id": "stock1",
         "end_node_id": "valve2",
         "curvature": 0.3,
         "along": 0.5,
         "select_state": "normal",
         "set_state": "set",
         "shape": "curved",
         "line_colour": "#505050",
         "line_width": 1,
         "fill_colour": "#505050",
         "arrowhead": {
            "shape": "diamond",
            "gap": 2,
            "width": 3,
            "front": 10,
            "back": -2
         }
      },
      "influence2": {
         "id": "influence2",
         "type": "influence",
         "label": "influence2",
         "start_node_id": "variable1",
         "end_node_id": "valve2",
         "curvature": 0.3,
         "along": 0.5,
         "select_state": "normal",
         "set_state": "set",
         "shape": "curved",
         "line_colour": "#505050",
         "line_width": 1,
         "fill_colour": "#505050",
         "arrowhead": {
            "shape": "diamond",
            "gap": 2,
            "width": 3,
            "front": 10,
            "back": -2
         }
      }
   },
   "scenarios": {
      "default": {
         "simulation_settings": {
            "start_time": 0,
            "end_time": 100,
            "nstep": 100,
            "display_interval": 1,
            "integration_method": "euler1"
         }
      }
   }
}
